export const ADD_UNPACKED_ITEM = "ADD_UNPACKED_ITEM";
export const CHANGE_PACKED_STATUS = "CHANGE_PACKED_STATUS";
export const CHANGE_ALL_TO_UNPACKED = "CHANGE_ALL_TO_UNPACKED";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const EDIT_ITEM = "EDIT_ITEM";
